# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social'),
        ),
    ]
