# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprodutocompra',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Quantidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemprodutovenda',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='Quantidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemservicocompra',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='Quantidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemservicovenda',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=15, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
