# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faturapagamento',
            old_name='pedidoCompra',
            new_name='pedido_compra',
        ),
    ]
